### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by otary** [suchjs/reregexp#13]
对于.*之类的正则，生成的字符乱码

**Comment by fefit** [comment]
@otary  这个跟 `.` 字符类能匹配的字符码点范围有关系，这些码点范围内的字符在js里编码展示的时候就会出现所说的乱码。考虑到有可能有如你所说的这种想让 `.` 字符只生成某些能正常展示的字符的需求，我来加一个配置项，这样你可以自定义 `.` 能匹配的字符码点范围，好满足不同情况的需要。

**Comment by fefit** [comment]
@otary 亲，新发布了一个版本1.6.0，在配置上增加了字段 `charactersOfAny`，可以全局配置，比如这样：
```javascript
// 设置全局将 '.' 解析为\w所指向的字符范围 
ReRegExp.charactersOfAny = CharsetHelper.points.w;
console(/^\w$/.test(new ReRegExp(/./).build())); // true
```
也可以在对应实例中覆盖全局或单独指定：
```javascript
const re = new ReRegExp(/./, {
    charactersOfAny: [[97, 122], [65,90]] // . 将解析为小写字母a到z或者大写字母A-Z
});
console.log(/^[a-z]$/i.test(re.build())); // true
```
也可以自定义一个生成方法来代替默认针对 '.' 字符类的生成方法：
```javascript
const re = new ReRegExp(/./, {
    charactersOfAny: (flags) => {
         if(flags.s){
             // 当flags包含dotAll，返回某个字符
         }
         // 默认返回某个字符
    }
});
```
不知道这样是否能满足你的需求了，如果还有其它问题，欢迎随时反馈~感谢!

**Comment by otary** [comment]
感谢回复，还是有点小遗憾，因为我想随机生成一部分中文字符，于是我加了如下配置：`charactersOfAny: [[97, 122], [65,90], [19968, 40869]]` ，但依然是会返回乱码，不过如果只生成英文字母，那是可以了

**Comment by fefit** [comment]
@otary 能方便把返回的乱码字符贴一下吗？

**Comment by otary** [comment]
正则：`(\d+)aa(\d+)bb.*`

生成10条：
````
08721aa23799bb崃缀宔槶宿

5469aa68774bb陵菍

3200aa9bb昁楾侪涣

73681aa89888bb铁阥羔

5aa9bb噱閙

8aa1bb

07aa1bb壽瀉軞繎垒

1763aa34381bb莗

63036aa372bb浝

451aa9bb渪寨

```

**Comment by fefit** [comment]
@otary 这些字符的确都在设置的字符编码范围内，包括可能出现的繁体字、偏旁部首等 [https://en.wikipedia.org/wiki/CJK_Unified_Ideographs_(Unicode_block)](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs_(Unicode_block))，看你的需求是不是想只展示英文、数字、中文且只展示简体字，这样就比较难办了，因为简体字的大部分并不在一个固定的码点范围内 [https://github.com/jpatokal/script_detector/blob/master/lib/chinese_detector.rb#L2894](https://github.com/jpatokal/script_detector/blob/master/lib/chinese_detector.rb#L2894) 可能得自行整理一份类似的范围列表了
