### ISSUE TITLE
IMPORT CDN

### ISSUE THREAD

**Issue by michael-jochmann** [suchjs/reregexp#16]
Hi,

we try to import like:

`import { ReRegExp } from 'https://esm.run/reregexp'`

but we get this error:

"Uncaught SyntaxError: The requested module 'https://esm.run/reregexp' does not provide an export named 'ReRegExp'"

alternative:

`import ReRegExp from 'https://esm.run/reregexp'`

leads to this error:

"TypeError ReRegExp is not a constructor at: TypeError: ReRegExp is not a constructor"

please help us.

LG micha

**Comment by fefit** [comment]
@michael-jochmann Sorry for being late to see the issue，from your description,  you may use the package in a `deno` environment with a remote  import. I saw the remote cdn package 'https://esm.run/reregexp' has wrapped the default export for twice time, i don't know why it doing like that, but if you need to import the final `ReRegExp` class, you may do like this:
```javascript
import { default as mod } from 'https://esm.run/reregexp';
const ReRegExp = mod.default;
const re = new ReRegExp(/\w+/);
re.build();
```
 thx for your issue~!

**Comment by michael-jochmann** [comment]
thx for your fast answer, we will try it.

yesterday i got it working with:

`import reregexp from 'https://cdn.skypack.dev/reregexp';`

const valueGenerator = new reregexp(`/${attributePattern}/`, {
            namedGroupConf: {
              override: ['Sex', 'SEX', 'HH', '88', 'XXX'],
            },
          });

lg micha
