### ISSUE TITLE
Doesn't work in ESM (types don't align with runtime API)

### ISSUE THREAD

**Issue by kaiyoma** [suchjs/reregexp#24]
This package works fine from a CJS module, but if I try to convert to ESM, I get this error:

```
TypeError: ReRegExp is not a constructor
```

My code is pretty simple:

```
import ReRegExp from 'reregexp';

const reregexp = new ReRegExp(...);
```

**Comment by kaiyoma** [comment]
Ah, I forgot that I need to reference `ReRegExp.default`, which works at runtime, but throws a type error.

**Comment by fefit** [comment]
@kaiyoma sorry for the late reply, the library does not support ESM module, but you can still import like this in an ESM project:

```javascript
// in old versions before 1.6.1
import re from 'reregexp';
const ReRegExp = re.default;
const r1 = new ReRegExp(/ab?c/);
```

I have added a new version v1.6.1 to add ESM export support in package.json, the nesting of `default` has been reduced in this version:

```javascript
import ReRegExp from 'reregexp';
const r1 = new ReRegExp(/ab?c/);
```
I don’t know what the type error you mentioned specifically refers to?

If there are still problems according to the above usage, can you provide a detailed error message?

**Comment by kaiyoma** [comment]
Ah yes, you described the situation perfectly. I just tried 1.6.1 and it works great! No need for `.default` and no type errors. Thanks for the quick fix!
