### ISSUE TITLE
能否生成升序或降序的数据呢

### ISSUE THREAD

**Issue by createNewLine** [suchjs/reregexp#30]
例如我的正则是这样的: /\d\d/
一次性生成十条数据后是这样的: 00, 01, 02, 03, 04......09
生成一组有规律的升序或降序的数据

**Comment by fefit** [comment]
@lslashub 正则生成字符的时候都是随机生成符合正则规则的字符，这种有规律的串可能更适合通过函数去控制生成，虽然目前库的生成逻辑不太好实现你的需求，但是有个hack的方式或许可以参考一下：
```javascript
import ReRegExp from 'reregexp';
let curNum = 0;
const orderNumber = [];
Object.defineProperty(orderNumber, 0, {
  get() {
    const value = curNum > 9 ? curNum.toString() : '0' + curNum;
    curNum++;
    return value;
  },
});
const re = new ReRegExp(/[a-z]{1,2}(?<orderNumber>\d\d)/, {
  namedGroupConf: {
    orderNumber,
  },
});
console.log(re.build());
console.log(re.build());
console.log(re.build());
console.log(re.build());
console.log(re.build());
console.log(re.build());
console.log(re.build());
```
`namedGroupConf` 的配置可以设定命名分组 `orderNumber` 的覆盖数据，每次分组 `build` 生成字符串会从覆盖数组数据里随机取一条并验证返回的字符是否符合分组的正则匹配，作为分组生成结果的替代数据。因此这里可以通过 `get` 函数来控制生成的值。运行示例：[https://playcode.io/1990393](https://playcode.io/1990393)

**Comment by fefit** [comment]
@lslashub 我先关掉这个issue啦，如果有问题或者想法可以继续讨论了~
